#!/usr/bin/php
<?php
$xml=simplexml_load_file($argv[1]);
// findtext($xml->body->children(),'');
findtext($xml);

function findtext($arr,$path=array()) {
	// print "-----------------------\n";
	// print_r($arr);
	// print "-----------------------\n";
	// if (!is_object($arr) && !is_array($arr)) {
	// 	print "WTF is it?\n";
	// 	// print_r($arr);
	// 	if (strlen($arr))
	// 		print "$arr\n";
	// 	return;
	// }
		
	foreach ($arr as $k=>$v) {
		$name=$k;

		switch ($name) {
			case "a":
			case "h1":
			case "h2":
			case "h3":
			case "h4":
			case "h5":
			case "h6":
			case "ol":
			case "ul":
			case "li":
			case "p":
			case "i":
			case "em":
			case "strong":
			case "small":
			case "b":
			case "div":
			case "span":
			case "center":
				print '/'.join($path,'/').'/'.$name;
				
				$text=(string)$v;
				$text=preg_replace('/\s+/',' ',$text);
				if (strlen(trim($text))) {
					// print " ".str_repeat("*",strlen($text)/10);
					print " ".$text;
					// print $name."=$text\n";
					// print substr($text,0,7)."\n";
					// if (substr($text,0,7) == "Griffin") {
						// print "found it: \n";
						// print_r((string)$v);
					// }
				}

				print "\n";
				break;
			default:
				// print "??? $name\n";
				break;
		}
		
		if ($v instanceof SimpleXMLElement) {
			if (count($v->count())) {
				findtext($v->children(),array_merge($path,array($name)));
			}
			else
				findtext(get_object_vars($v),array_merge($path,array($name)));
		}
	}
}

?>